# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy_to_lambda:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Zips get_games.py
      - name: Zip get_games function
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq ./Backend/Lambda_Functions/get_games/get_games.zip ./Backend/Lambda_Functions/get_games/get_games.py
          
      # Runs a set of commands using the runners shell
      - name: Deploy get_games function to lambda function get_games
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: get_games
          zip_file: Backend/Lambda_Functions/get_games/get_games.zip





