
name: Deploy game listing service

on:
  # Triggers the workflow on push but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_to_lambda:
    name: Deploy function to AWS Lambda
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Zips get_games.py
      - name: Zip get_games function
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq ./Backend/Lambda_Functions/get_games/get_games.zip ./Backend/Lambda_Functions/get_games/get_games.py
          
      # Deploys the script to AWS Lambda
      - name: Deploy get_games function to lambda function get_games
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          function_name: get_games
          zip_file: Backend/Lambda_Functions/get_games/get_games.zip

  test_request:
    name: Test request (Integration with AWS Lambda)
    needs: deploy_to_lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
        #Setting up python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

        #Install necessary dependencies for the test
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

        # Runs the test request script
      - name: Run test request script
        run: python ./Backend/Tests/get_games/test_get_games.py





